name: kata_jane
description:
publish_to:

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.1
  flutterfire_cli: ^1.0.0
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.4
  path: ^1.8.1
  intl: ^0.18.1
  image_picker: ^1.1.2
  esewa_flutter_sdk:
    path: ./esewa_flutter_sdk
  provider: ^6.1.2
  change_app_package_name: ^1.3.0
  firebase_storage: ^12.1.1
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  firebase_messaging: ^15.0.3
  map_launcher: ^3.3.1
  geocoding: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/
    - assets/logos/
    - assets/images/

